---
title: Strike Force For Change
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: true
    published: true
  representatives:
    title: Representatives
    output: false
  successes:
    title: Successes
    output: true
  uploads:
    title: Uploads
    output: true
subtitle: Strike Force For Change, an Indivisible group
background-image: "/uploads/shutterstock_PurpleLimeSmash.jpg"
email: strikeforceforchange@gmail.com
facebook_username: SFFCIndivisible/
twitter_username: 
footer-title: Grassroots, Straight-Up
base-url: 
url: 
member-count: 105
paginate: 10
