---
title: Strike Force For Change, An Indivisible Group
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: true
  representatives:
    title: Representatives
    output: true
  uploads:
    title: Uploads
    output: true
email: strikeforceforchange@gmail.com
Subtitle: Grassroots - Straight-Up
background-image: "/uploads/shutterstock_PurpleLimeSmash.jpg"
facebook_username: https://www.facebook.com/groups/780265365460064/
Field name: 
