---
title: Strike Force For Change
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: true
  representatives:
    title: Representatives
    output: true
  uploads:
    title: Uploads
    output: true
email: strikeforceforchange@gmail.com
Subtitle: An Indivisible Group
background-image: "/uploads/shutterstock_PurpleLimeSmash.jpg"
facebook_username: https://www.facebook.com/groups/780265365460064/
subtitle: Grassroots Straight-Up
